services:
  sbs:
    image:  yuwenhaibo/sbs:latest
    environment:
      - SNI=www.samsung.com
    container_name: sbs
    ports:
      - "44339:443"
    volumes:
      - sbs-volume:/opt/singbox/config
volumes:
  sbs-volume: